---
- include: build_dockerimage.yml
- include: create_volumes.yml
- include: template_compose_file.yml

- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0554
  register: systemd_unitfile

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_unitfile.changed

- name: Restart service
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: dockerimage.changed or dockercompose_file.changed or systemd_unitfile.changed
